#:schema https://mise.jdx.dev/schema/mise.json

[plugins]
	taplo = "https://github.com/Okeanos/asdf-taplo"

# See https://github.com/jdx/mise/blob/main/registry.toml for what is officially available
# Everything else is just declared as a reference to keep track of it.
[tools]
	editorconfig-checker = "3.1.2" # GitHub Actions sha256sum=3fd4fc81e5077f89faddb71ff05a5d6e2983b8c3953d1b1b6663c7245300e653
	gitleaks = "8.23.1"            # GitHub Actions sha256sum=6fac0fe2602d8aeaf5135b7a957bbac27984b1ad14def0574be0e115e3d73252
	markdownlint-cli2 = "0.17.2"
	shellcheck = "0.10.0"
	shfmt = "3.10.0"
	taplo = "0.9.3"                # GitHub Actions sha256sum=71d655dc3f69ce30454cfade92fdbe846c0ba4aa3afa68f3ff0d216966d0d3c2
	yamllint = "1.35.1"
